### ISSUE TITLE
Bug with SpotifyControls

### ISSUE THREAD

**Issue by kaiserdj** [AlexisJonsson/AlexisJonsson.github.io#1]
The theme is beautiful, I would love to use it. But having the [SpotifyControls](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/SpotifyControls/) plugin, it gets bogged down by leaving an empty section below, and on the top bar there are invisible buttons that are placed on top of others and change songs all the time.

Example: 

https://user-images.githubusercontent.com/5487950/125337635-89dfd000-e34f-11eb-8a6c-6c959d14f6c2.mp4

**Comment by AlexisJonsson** [comment]
Thanks!
I've redone how the user panel is handled now so it should function properly.
![Screenshot 2021-07-13 112708](https://user-images.githubusercontent.com/23642164/125427892-c0763ae7-ecb5-4365-af70-5c67e252a19f.png)
