### ISSUE TITLE
No blur effect on top sever list

### ISSUE THREAD

**Issue by aunight** [AlexisJonsson/AlexisJonsson.github.io#11]
![image](https://user-images.githubusercontent.com/52199445/126771366-283d8ccd-e4d6-4e25-a92f-08029c26e2dc.png)
I have using the newest version and disable all the other theme or plugin.
But it still didn't work.
Please fix.
And I hope server icon can be more bigger like original horizontal sever list.

**Comment by LarveyOfficial** [comment]
On newest, seems I dont have this issue.

**Comment by trashcatt** [comment]
I'm having the same problem.

**Comment by aunight** [comment]
I find the question.
You need to enable Hardware acceleration.
And you can have blur effect.

**Comment by AlexisJonsson** [comment]
This happens when you have Hardware Acceleration off.

Try enabling it in Discord Settings 
![image](https://user-images.githubusercontent.com/23642164/126881913-c4d40b40-34f2-405d-8812-ab30794242c4.png)

**Comment by AlexisJonsson** [comment]
> ![image](https://user-images.githubusercontent.com/52199445/126771366-283d8ccd-e4d6-4e25-a92f-08029c26e2dc.png)
> I have using the newest version and disable all the other theme or plugin.
> But it still didn't work.
> Please fix.
> And I hope server icon can be more bigger like original horizontal sever list.

Have you tried looking in the theme file?

You can edit these two lines to be whatever size you want for the server list size.
    --server-icon-size: 32px;  /* Size of the server icons */
    --server-outer-margin: 14px;  /* Spacing between the edge of the container and the server icons.*/

Hope that helps!
