### ISSUE TITLE
Glitchy channel when sending messages pt2

### ISSUE THREAD

**Issue by LarveyOfficial** [AlexisJonsson/AlexisJonsson.github.io#12]
It seems that after the update the issue from issue #10 Still happens

https://larvey.sucks-at.life/krjc203wc9a

**Comment by AlexisJonsson** [comment]
I finally found what was causing it so now it is properly fixed in the latest update. 👍

**Comment by AlexisJonsson** [comment]
If you need any other help or request features I made a support server. :) [https://discord.gg/mVDzu73Y26](https://discord.gg/mVDzu73Y26)
