### ISSUE TITLE
Theme: In minimal mode, User settings button disappears upon hover

### ISSUE THREAD

**Issue by Jaluvshuskies** [AlexisJonsson/AlexisJonsson.github.io#15]
https://user-images.githubusercontent.com/29661044/127892652-6abf0c86-09cd-4994-92ad-d37719fedba8.mp4

With the Alexis theme, when better discord's minimal mode is enabled, the "user settings" button at the top disappears when hovering over it. It appears as though I have to uninstall the theme via file explorer in %appdata% in order to get around this. Restarting discord did not change this, and I am unsure of any way to access users settings

**Comment by AlexisJonsson** [comment]
Yeah minimal mode is not supported by the theme, I'll make sure that's actually mentioned in the about page for the theme.

Also if you have any other requests or feedback, feel free to [join the support server ](https://discord.com/mVDzu73Y26)

**Comment by Jaluvshuskies** [comment]
> Yeah minimal mode is not supported by the theme, I'll make sure that's actually mentioned in the about page for the theme.
> 
> Also if you have any other requests or feedback, feel free to [join the support server ](https://discord.com/mVDzu73Y26)

I am receiving a 404 error when attempting to join the discord server. Just wanted to let you know! And thank you

**Comment by AlexisJonsson** [comment]
Oh whoops sorry! I did .com rather than .gg haha

Here you go :) [https://discord.gg/mVDzu73Y26](https://discord.gg/mVDzu73Y26)
