### ISSUE TITLE
A suggestion to improve Korean translation

### ISSUE THREAD

**Issue by qkdxorjs1002** [AlexisJonsson/AlexisJonsson.github.io#18]
Hi, Thank you for providing a clean theme.
I suggest improvement for natural korean translation. 

In the CSS File 'https://alexisjonsson.github.io/BetterDiscordAddons/Themes/modern-discord.theme.source.css'
```
.container-3w7J-x a[aria-label="스테이지 채널"]:after,.containerDefault--pIXnN a[aria-label*="(음성 채널)"]:after {
    content: "연결하다"
}
```
"연결하다" is weird to use on button that mean "Make a connection" in korean. So, "연결하기" is more natural expression.

Thanks.

**Comment by AlexisJonsson** [comment]
Hi!

Thank you so much for the feedback, I just used google translate for my initial translation so to have it verified by someone who knows the language is really valuable.

I'll make sure to release an update for it ASAP.

If you want to, feel free to join my server for the theme if you have any more feedback or feature requests :) [https://discord.gg/mVDzu73Y26](https://discord.gg/mVDzu73Y26)
