### ISSUE TITLE
Problem with voice chat control icons

### ISSUE THREAD

**Issue by qkdxorjs1002** [AlexisJonsson/AlexisJonsson.github.io#19]
**Environment**
<img width="226" alt="스크린샷 2021-08-05 오후 7 45 27" src="https://user-images.githubusercontent.com/3241479/128337667-df17e6e1-cbdf-4ff0-b961-c4ac0dbad91f.png">

**Problem**
"Turn on Camera" and "Turn on Screen share" button icons are miss-placed.

<img width="211" alt="스크린샷 2021-08-05 오후 7 37 32" src="https://user-images.githubusercontent.com/3241479/128336796-f50c5993-ab65-44fe-8587-ac5e79f1b9b9.png">

**Comment by AlexisJonsson** [comment]
What's your zoom level?
![image](https://user-images.githubusercontent.com/23642164/128369882-692078e6-54ea-4068-a0d3-e82a07506923.png)

What's your language on the client?

And what plugins do you have installed?

**Comment by qkdxorjs1002** [comment]
**I tested on macOS 11.5.1.**

**Scale**
 - No options for scaling

**Language**
 - Korean

**macOS Res**
 - Physical: 2560x1600
 - Logical: 2880x1800
 - Logical (Retina Scaled): 1440x900

**Plugins**
 - BDFDB v1.7.13
 - BiggerStreamPreview v1.0.7
 - DoubleClickToEdit v9.2.2
 - ImageUtilities v4.4.5
 - PluginRepo v2.2.5
 - ThemeRepo v2.2.7
 - ThemeSettings v1.3.3
 - ZeresPluginLibrary v1.2.31

It seems to have difference with where i joined channel.

**Channel 1**
<img width="292" alt="스크린샷 2021-08-07 오전 8 21 38" src="https://user-images.githubusercontent.com/3241479/128580072-5bc04755-e740-4474-94ae-e1703b80c142.png">

**Channel 2**
<img width="292" alt="스크린샷 2021-08-07 오전 8 21 50" src="https://user-images.githubusercontent.com/3241479/128580079-72b751b7-d88a-4ff0-889c-c23be3f62055.png">

**Comment by qkdxorjs1002** [comment]
**Additional Information**
I guess "line-height" cause this problem.

**Find the container that have wrong padding(?)**
<img width="259" alt="스크린샷 2021-08-07 오후 4 48 01" src="https://user-images.githubusercontent.com/3241479/128593057-6039770c-63f9-4769-9b19-40528e315339.png">

**Uncheck "line-height: 16px;"**
<img width="259" alt="무제" src="https://user-images.githubusercontent.com/3241479/128593059-664fa926-aa54-41ae-ac49-1aa630ed13eb.png">

<img width="532" alt="스크린샷 2021-08-07 오후 4 50 22" src="https://user-images.githubusercontent.com/3241479/128593062-a01d5386-8fb6-460e-8173-3d0749e61d96.png">

<img width="213" alt="스크린샷 2021-08-07 오후 4 54 46" src="https://user-images.githubusercontent.com/3241479/128593219-612aeea0-2ada-4724-8601-05b49cd0fc10.png">

I don't know this solution solve problem....or cause potential bugs...😅
Please let me know is this correct.

**Comment by AlexisJonsson** [comment]
Thank you for the detailed information ;)

I pushed and update (version 21.08.07c) that sets the line-height of that container to "unset" and I'm also setting the max size to 20px so hopefully that will resolve the issue.

Let me know if that solves the issue and if not we'll have to try something else :)

**Comment by qkdxorjs1002** [comment]
@AlexisJonsson Thank you! Problem is solved.

**Comment by AlexisJonsson** [comment]
Awsome! Glad to hear 👍
