### ISSUE TITLE
VC Options Glitch

### ISSUE THREAD

**Issue by mb1541def** [AlexisJonsson/AlexisJonsson.github.io#21]
Whenever I join a voice chat, the option for screen share and microphone toggle is overlapping each other
 in the bottom-left gui.

![This](https://user-images.githubusercontent.com/71204656/128636818-e6450491-b014-440c-92b1-8fc75dc4bde8.png)

**Comment by AlexisJonsson** [comment]
Oh strange.

What language is your discord in and do you have any plugins installed?

**Comment by mb1541def** [comment]
**My language:**
English (U.S)

**Discord Version:**
Canary 92815 (1bf8462)
BetterDiscord 1.2.1
Host 1.0.37
Windows 10 64-Bit (10.0.19043)

Theme Version 21.08.07e

**Plugins installed:**
BDFDB
BetterBannedUsers
BetterFolders
BetterFormattingRedux
BetterFriendList
BetterSearchPage
BlurNSFW
BugReportHelper
CallTimeCounter
CanaryLinks
CharCounter
CreationDate
CustomStatusPresets
DisableStickerSuggestions
Discord Experiments
GuildAndFriendRemovalAlerts
GuildProfile
ImageUtilities
LastMessageDate
MessageUtilities
NotificationSounds
Open in YouTube
PersonalPins
PlatformIndicators
PluginRepo
SpotifyControls
SpotifyListenAlong
ThemeRepo
ThemeSettings
Translator
TypingUsersAvatars
User VoiceShow
WhoReacted
ZeresPluginLibrary

**Comment by AlexisJonsson** [comment]
Does it still overlap if you disable the plugins and restart the app? Because it's most likely one of them causing a change in the call bar area.

**Comment by AlexisJonsson** [comment]
In the plugins channel in my support server you can see what plugins are tested and supported by the theme. [https://discord.gg/mVDzu73Y26](https://discord.gg/mVDzu73Y26)

**Comment by mb1541def** [comment]
It still overlaps after I disable all of my plugins and addons from BetterDiscord.

**Comment by AlexisJonsson** [comment]
I see you're running Canary, have you tried normal discord?

**Comment by mb1541def** [comment]
I have tried normal discord, and now it does not overlap. Probably a gui bug on canary's end.

**Comment by AlexisJonsson** [comment]
Ah I see, we'll I'll have a look at canary and see if I can hopefully fix that up either way. Thanks for the heads up!

**Comment by mb1541def** [comment]
No problem.
