### ISSUE TITLE
Transparent bars and server background

### ISSUE THREAD

**Issue by BerkoSVK** [AlexisJonsson/AlexisJonsson.github.io#22]
The screenshot says it all, is it somehow possible or it has to stay like this?
![Screenshot_2](https://user-images.githubusercontent.com/66250098/129030145-e917f79a-d981-4377-93ab-15b6bcb28021.png)

**Comment by AlexisJonsson** [comment]
You need to make sure you have Hardware Acceleration enabled.
![image](https://user-images.githubusercontent.com/23642164/129030593-da6a0fc6-5135-46d0-a231-52e6aebde122.png)
