### ISSUE TITLE
[Question] Is there a way for me to get the channel icons code?

### ISSUE THREAD

**Issue by RUGMJ7443** [AlexisJonsson/AlexisJonsson.github.io#25]
I really like this theme but my friends don't but they do like the channel icons I am ok-ish at CSS but not the fancy "programming" side of it so I was wondering if anyone could give me the code for the channel icons I have had a go but the icons look "grainy" and only bits of the icon actually appear here's the code I've extracted so far: https://pastebin.com/FkxtpGf3 thanks in advance

**Comment by AlexisJonsson** [comment]
I'm honestly not a huge fan of people just copying my code. Many of the icons used is stuff I've made by myself too.

I might release a theme that only adds icons to channels but we'll have to see. My main focus is this theme.

**Comment by RUGMJ7443** [comment]
I am so sorry I didnt see any licence on this repo so I assumed it was open source

**Comment by warmbo** [comment]
Everything here is open source. License-wise that doesn't mean you can do what you want with it, it just means you can see it.
