### ISSUE TITLE
[Request / Question] Center Settings

### ISSUE THREAD

**Issue by Explsn** [AlexisJonsson/AlexisJonsson.github.io#26]
As of now the settings seem to be uncentered:
[image](https://uploadi.ng/KLCRgsfx)

Is it planned for the settings menu to be redesigned, or be centered? Any way I can do that myself?

**Comment by AlexisJonsson** [comment]
I'm doing a complete overhaul on settings, if you're interested in following the theme I got a dev server where I post updates and previews. [https://discord.gg/mVDzu73Y26](https://discord.gg/mVDzu73Y26)
