### ISSUE TITLE
[ BUG ] Issue whenever in a dm call while screensharing | Issue that doesn't let you screenshare

### ISSUE THREAD

**Issue by jqww** [AlexisJonsson/AlexisJonsson.github.io#28]
1. Whenever you are inside of a dm call with someone and you fullscreen their screenshare, you are unable to click any of the bottom buttons including the exit button whenever you are trying to move your cursor to the bottom, and sometimes text pushes above the black background.
![DiscordCanary_8nwIrEh1OG](https://user-images.githubusercontent.com/53201564/130274239-7df96439-c597-4bcb-89e9-339e7315a0e7.png)

2. Whenever you are trying to screnshare inside of a server, the mute icon and the screenshare seem to collide into each other and I am unable to screenshare.
![DiscordCanary_ASgo1dsMnO](https://user-images.githubusercontent.com/53201564/130273636-2daf542e-b873-45f8-a49e-bf19de8e2534.png)

**Comment by jqww** [comment]
Upd: It seems to just be at that specific spot because streaming that game does a similar bug
![DiscordCanary_4Ejs1hOG5S](https://user-images.githubusercontent.com/53201564/130278219-f7fb4fdc-9c2d-4c28-bbaa-13054a1baa88.png)

**Comment by AlexisJonsson** [comment]
For some reason Discord Canary handles that area differently, haven't found a fix for it yet but if you want a temporary solution you could use standard Discord.

**Comment by AlexisJonsson** [comment]
1. That's a known issue, working on finding a fix!

**Comment by jqww** [comment]
Alright thank you very much for the help!
