### ISSUE TITLE
Disconnect from a voice call

### ISSUE THREAD

**Issue by AshFennix** [AlexisJonsson/AlexisJonsson.github.io#3]
![image](https://user-images.githubusercontent.com/3123226/125372525-e986ad00-e348-11eb-9345-c7de6dde9174.png)
Is there a disconnect from call button?

**Comment by AlexisJonsson** [comment]
Are you still experiencing the same error? I rewrote the css for that area so it should display properly now.
![Screenshot 2021-07-13 113017](https://user-images.githubusercontent.com/23642164/125428351-2927b979-5f2a-4b06-b4e6-d4ab8179c3d2.png)

**Comment by AshFennix** [comment]
still the same on v21.07.13
tried disabling all plugins, still missing.

Im on Linux if that matter for whatever reason

**Comment by AlexisJonsson** [comment]
Have you tried restarting discord and reinstalling the theme?

Also what language is your discord set to? It might help to change it to English temporarily to see if that helps.

**Comment by AshFennix** [comment]
Already in English, still having the issue after deleting the them, restarting, reinstalling via the repo

**Comment by AlexisJonsson** [comment]
I've now pushed an update that alters how the Krisp button is hidden from that bar. Let me know how that works!

**Comment by AshFennix** [comment]
Works Ty
