### ISSUE TITLE
BetterDiscord update prompt blocked by "click to update"

### ISSUE THREAD

**Issue by OwlCacone** [AlexisJonsson/AlexisJonsson.github.io#31]
When the BetterDiscord update prompt appears at the bottom of the screen, the plugin name, or "all" button is blocked by the "click to update" text.

**Comment by OwlCacone** [comment]
Forgot to add picture
![image](https://user-images.githubusercontent.com/88836728/130789553-4f1dd34c-06cd-49ba-b9bc-738633342b0a.png)

**Comment by AlexisJonsson** [comment]
This should now be fixed with the latest update!
