### ISSUE TITLE
Font changed on its own. Click hand not appearing anymore.

### ISSUE THREAD

**Issue by KeryWT** [AlexisJonsson/AlexisJonsson.github.io#34]
Hi, the theme is beautiful but today a few issues appeared. 
Font changed on its own and the hand that should appear when hovering something clickable isn't appearing anymore.
I attached a screenshot showing the issues.
I can already tell you that also some friends of mine with the same theme are having these issues.
[https://imgur.com/a/SBjX7vf](url)

**Comment by KeryWT** [comment]
Oh okay, i understand. Maybe an option to set a custom font would be cool. Or maybe just a toggle to switch back to the default font. That would be amazing to have. I don't know why but discord feels kind of weird with this font xD. Maybe it's a bit too thin, or I don't know 🙃

**Comment by KeryWT** [comment]
So, I also found a conflict with the plugin [BetterVolume](https://github.com/Zerthox/BetterDiscord-Plugins/blob/master/v1/BetterVolume.plugin.js)
If the theme is active you can't see or use the arrows that let you adjust the volume above 200. Normally the plugin lets you also click on the volume value and write it directly, but with this theme it doesn't let you click now.
I'm pretty sure BetterVolume was working fine before this update, or maybe I just never noticed the issue (less likely).
Maybe the latest update to the theme broke the plugin. I don't know if I should open another issue or leave this here?? I hope you can help anyway. I attached some screenshots again. 
[Theme ON](https://lensdump.com/i/ZXvf2a)
[Theme OFF](https://lensdump.com/i/ZXvFJe)

**Comment by AlexisJonsson** [comment]
1. Yeah I totally agree, I want to add more customization options once the theme is more polished.
2. That should be fixed now with the latest update, let me know if you're still having those issues. 🙂

**Comment by KeryWT** [comment]
Ok, the volume is working fine now. Thanks for your help

**Comment by deviljin112** [comment]
Hello I have an issue with the new commit as it broke my font. Font is now set as a super basic Microsoft-ish font. Maybe it's an issue with my OS (Linux), and it's missing some font but the font looks so bad and basic compared to what it used to be. Could we possibly get a custom parameter in BetterDiscord Edit page for the theme, to set our own font? Would be great for customization. If that's not possible, happy to assist in fixing this issue. Thanks.

**Comment by AlexisJonsson** [comment]
I'll try and fix it up for the next update @deviljin112 , let me know if that fixes it for you once the update is out!
