### ISSUE TITLE
Giant space in profile settings

### ISSUE THREAD

**Issue by Triple4s** [AlexisJonsson/AlexisJonsson.github.io#35]
It correlates with the plugin "StatusEverywhere"

![Screenshot (4930)_LI](https://user-images.githubusercontent.com/87712211/133623124-cf70f9fb-ff05-47e8-b8d1-e732b90df668.jpg)

**Comment by AlexisJonsson** [comment]
Oh that's not right, hmm. I'll have a look at it and see if I can find a fix.
