### ISSUE TITLE
User Settings isn't working.

### ISSUE THREAD

**Issue by akyiiw** [AlexisJonsson/AlexisJonsson.github.io#5]
"Translate this text into Portuguese - BR if necessary."

**Good** day, I was looking for new themes, and I saw Alexis Modern. At first I thought the Windows 11 theme was amazing, I thought it was perfect. But when entering, I noticed some glitches like in the lower left corner where a part goes through the Upload button (Shadow) and when you click on its name and mouse over User Settings.

The problem is that when you hover over the User Settings (Button) it disappears and you can't click. To remove the theme, I had to go to C:\Users\\appdata\Roaming and Better Discord to delete this theme. Please fix this. Thanks.

![image](https://user-images.githubusercontent.com/87397879/125535783-860ea8a6-b773-4f4e-b763-ba4e09939771.png) The Shadow 

![image](https://user-images.githubusercontent.com/87397879/125535819-e6218add-08cf-4b18-bda2-62c6eeccfa54.png) The glitch (In the screenshot the mouse does not appear)

**Comment by AlexisJonsson** [comment]
Make sure you don't have compact mode turned on in better discord or any other themes enabled at the same time.

**Comment by AlexisJonsson** [comment]
Also try and disable some plugins that might alter your theme.
