### ISSUE TITLE
Bug duplicate image and background texts

### ISSUE THREAD

**Issue by kaiserdj** [AlexisJonsson/AlexisJonsson.github.io#6]
I updated the discord last night and from that moment the visualization of the upper area has been bugged, looking transparent and repeating the image of the server
![image](https://user-images.githubusercontent.com/5487950/125974714-7d98d1dd-be07-46ea-a516-742540667fca.png)

**Comment by kaiserdj** [comment]
Versión discord and betterdiscord:
Stable 90176 (337b0b5)
BetterDiscord 1.2.0
Host 1.0.9002 Windows 10 64-Bit (10.0.22000)

**Comment by AlexisJonsson** [comment]
Make sure that you have "Hardware Acceleration" enabled since the blur effect won't display otherwise.

![Screenshot 2021-07-17 155557](https://user-images.githubusercontent.com/23642164/126039297-a5e56668-90bc-49a2-89c2-bed25e8020ff.png)
