### ISSUE TITLE
Misaligned buttons on Mac

### ISSUE THREAD

**Issue by KritPaoIn** [AlexisJonsson/AlexisJonsson.github.io#65]
<img width="304" alt="image" src="https://user-images.githubusercontent.com/92923965/146726178-7484ab04-a673-462e-8323-bfe287a83081.png">

**Comment by DeudzXD** [comment]
this is also happening to me on windows

**Comment by RickRollMaster101** [comment]
That also happens to me on linux

**Comment by OlavWolfiken** [comment]
Go to the FAQ channel on the [theme support server](https://discord.gg/HsVyDZ76)

**Comment by OlavWolfiken** [comment]
#67
