### ISSUE TITLE
BEFORE POSTING ANY NEW ISSUE, PLEASE READ THE F.A.Q.

### ISSUE THREAD

**Issue by OlavWolfiken** [AlexisJonsson/AlexisJonsson.github.io#67]
### Before posting any new issue on here, please make sure it wasn't already addressed, by reading the FAQ found on the theme's support server found [here](https://discord.gg/mVDzu73Y26)! Thank you!

**Comment by HirschBerge** [comment]
Just put a FAQ here like everyone else. Do you need members on your discord that badly?

**Comment by osiixy** [comment]
For the others to spare some time here is the important part from the server's FAQ
(content of the below mentioned file)
`@import url("https://onkofonko.github.io/theme/fixedsource.css");`
`@import url("https://onkofonko.github.io/theme/fixes.css");`

> THEME LOOKS WRONG?
> 
> The theme has a few bugs at the moment caused by discord updates. The developer is working hard to fix them. 
> 
> A temporary fix has been provided by @OnkoFonko. Thanks mr, 
> To apply the temporary fix by @OnkoFonko follow these steps: 
> 1. Copy the contents of the file provided
> 2. Press CTRL + , to go to the Settings and go to BetterDiscord tab of the Settings
> 3. Open the Custom CSS dropdown to make sure that the Custom CSS switch is turned on
> 4. Go to the Custom CSS tab of the Settings (make sure old fixes are removed) and paste the copied contents of the fix into the pop-up
> 5. Press the Save button (💾), and then the Update button (🔄)
> 6. And just to be sure, press CTRL + R to refresh the Discord app
> And you're done!

**Comment by OlavWolfiken** [comment]
> Do you need members on your discord that badly?
@HirschBerge 
It is not my server, either way it's better to have the theme's userbase on there in case of any updates from the developer

**Comment by HirschBerge** [comment]
> > Do you need members on your discord that badly?
> 
> @HirschBerge, it is not my server, either way it's better to have the theme's userbase on there in case of any updates from the developer

Are you  a contributor? If not, I don't give a shit about your opinion. If it's not your project, just kindly stop inserting yourself into their process.

**Comment by Slddev** [comment]
> Are you a contributor? If not, I don't give a shit about your opinion. If it's not your project, just kindly stop inserting yourself into their process.

Rude, he is just trying to help. Indeed it is more useful to have the userbase in the Discord server that way, everyone would be notified if a needed fix is there. No I am not a contributor, but I care about the users of the theme.
