### ISSUE TITLE
Highlight messages that mention you

### ISSUE THREAD

**Issue by AshFennix** [AlexisJonsson/AlexisJonsson.github.io#7]
Can you have messages that mention you highlight? Its really hard to spot them sometimes, esp in a really busy channel

**Comment by AlexisJonsson** [comment]
Yeah I can totally implement that again. The initial reasoning was that it looked a bit too much but I can do a more minimized version that still kind of highlights pings and mentions.

**Comment by AlexisJonsson** [comment]
Bit of a late reply but I forgot to mention here that this has now been implemented. 
I made a server for the theme where there's updates and where people can submit feedback [https://discord.gg/mVDzu73Y26](https://discord.gg/mVDzu73Y26)
