### ISSUE TITLE
Discord Support URLs disappear 

### ISSUE THREAD

**Issue by LarveyOfficial** [AlexisJonsson/AlexisJonsson.github.io#9]
I noticed in the source code that support.discord.com links get rewritten as "", but anytime I wanna send a support link or anything related to that its impossible to use the theme. Anyway that can be togglable or removed?

**Comment by AlexisJonsson** [comment]
I think that's from me removing the support button from the header bar, I can push an update to fix this now so it'll be live in a bit.

**Comment by AlexisJonsson** [comment]
Fixed now!
